title: 炎香樓 Yan Heung Lau
description: 台中市西區頂級創意粵式料理餐廳
lang: zh-Hant

url: "https://yanxianglou.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  news:
    output: true
    permalink: /news/:slug/

defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news-post"

restaurant:
  phone: "04-2329-9968"
  address: "台中市西區精誠八街"
  line_oa: ""
